app:
  message: Message sent to the RabbitMQ queue Successfully
server:
  port: 9090
#Specify rabbitMQ configuration
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    exchange: myExchange
    queue: myQueue
    routingKey: key